## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd

dataFrame = pd.DataFrame(data)
print(dataFrame)
print("-----------------")
print(dataFrame.loc[dataFrame.num_cars > dataFrame.family_size],["Psychologist","Teacher"])
print("------------------------")

print(dataFrame.loc[dataFrame.family_size <= 2],[dataFrame.num_cars >= 1])
print("-------------------------------")
print(len(set(dataFrame.job)))

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
-----------------
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4 ['Psychologist', 'Teacher']
------------------------
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1 [0    True
1    True
2    True
3    True
4    True
5    True
6    True
Name: num_cars, dtype: bool]
-------------------------------
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
import pandas as pd

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import pandas as pd
'''
x = pd.concat([fruit,weights], axis = 1)
print(x)
print("----")
print(np.mean(x.loc[:,"banana"]))
loc method did not work with indexing, will try using lists
instead of lists, dictionaries are more effiient since key is the fruit and value is weight, just combinign thenm then doign 
calculation would be efficient
'''


dictionaryFruits = {"Carrot":[],"Banana":[],"Apple":[]}
for index in range(0,10,1): #RANGE EQUALS AMOUNT OF TIMES IT WILL GO
  if fruit[index] == "carrot":      #if index = carrot, then append the weight at the same index where carrot is identified (for each fruit)
    dictionaryFruits["Carrot"].append(weights[index])
  elif fruit[index] == "banana":
    dictionaryFruits["Banana"].append(weights[index])
  elif fruit[index] == "apple":
    dictionaryFruits["Apple"].append(weights[index])


#print(dictionaryFruits)

for fruitName in dictionaryFruits:
  meanFruit = np.mean(dictionaryFruits[fruitName])
  print("fruitname: ", fruitName, meanFruit)




fruitname:  Carrot 2.5
fruitname:  Banana 6.0
fruitname:  Apple 6.5


In [ ]:
# Type your solution here


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
x = np.sort(course_name) #sort was never covered in class, which is already unacceptable
#furthermore, without any specification on HOW to sort, there is no way to check that my sort actually worked.
#lastly, without a sample output (as promised at the top of document, I feel very powerless. will bring up in OH)
indexNumPython = list(x).index("Python")
indexNumJS = list(x).index("JS")
indexNumExamples = list(x).index("examples")
indexNumPHP = list(x).index("PHP")
indexNumHTML = list(x).index("html")


print("Python Index:",indexNumPython)
print("JS index: ", indexNumJS)
print("examples index:", indexNumExamples)
print("PHP index:", indexNumPHP)
print("HTML index:", indexNumHTML)

Python Index: 2
JS index:  0
examples index: 3
PHP index: 1
HTML index: 4


In [ ]:
# Type your solution here
#since it specifically says numpy code, i will google and try to find a function that does this 
#since we did not learn anything remotely like this in class :)

firstCharacter = np.char.startswith(course_name,"P")
print("In order to be organized, I will print the array and then firstCharacter so it lines up")
print(course_name)
print(firstCharacter)


In order to be organized, I will print the array and then firstCharacter so it lines up
['Python' 'JS' 'examples' 'PHP' 'html']
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
print(student_id)
flippedArray = np.flipud(student_id)
print(flippedArray)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


In [ ]:
print(student_id)
student_id.sort()
print(student_id)
#three largest values are at the end
print(student_id[[-1,-2,-3]])

[1023 1671 1682 4532 5202 5241 6230]
[1023 1671 1682 4532 5202 5241 6230]
[6230 5241 5202]


In [ ]:
# Type your solution here

# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off
x = np.arange(100)
multipleThree = np.where(x%3==0)
multipleFive = np.where(x%5==0)
print(np.sum(multipleThree))
print(np.sum(multipleFive))
ntotalThreeAndFiveSum = np.sum(multipleFive) + np.sum(multipleThree)
print("total of three and five:", ntotalThreeAndFiveSum)


1683
950
total of three and five: 2633


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4) 
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
#3 rows and 4 columns

modifiedArray = arr
modifiedArray[:,[1,2]] = modifiedArray[:,[2,1]]
print(modifiedArray)

print("----------------------------")
modifiedArray[[0,1],:] = modifiedArray[[1,0],:]
print(modifiedArray)


[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
----------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
